<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-SatinRoad-18872202-c97e-44d5-bea5-feefc680f6aa</UserSecretsId>
        <RootNamespace>SatinRoad</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>
</Project>
