services:

  backend:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - satinroad-db:/app/data

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  satinroad-db: